groups:
  - name: flask-app-alerts
    rules:
      - alert: HighRequestRate
        expr: rate(request_count_total[1m]) > 1
        for: 30s
        labels:
          severity: warning
        annotations:
          summary: "High Request Rate"
          description: "More than 1 request/sec is being served by Flask for 30 seconds."

      - alert: HighRequestCountCreated
        expr: rate(request_count_created[1m]) > 1
        for: 30s
        labels:
          severity: warning
        annotations:
          summary: "High Request Creation Rate"
          description: "More than 1 new request/sec created for 30 seconds."

  - name: system-resource-alerts
    rules:
      - alert: HighMemoryUsage
        expr: process_resident_memory_bytes > 100000000
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "High Memory Usage"
          description: "Memory usage of Flask process exceeded 100MB."

      - alert: HighCPUUsage
        expr: rate(process_cpu_seconds_total[1m]) > 0.8
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "High CPU Usage"
          description: "CPU usage of the Flask process exceeded 80% for 1 minute."

  - name: prometheus-health-alerts
    rules:
      - alert: PrometheusJobDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Prometheus target down"
          description: "One or more Prometheus scrape targets are down."

      - alert: LongScrapeDuration
        expr: scrape_duration_seconds > 1
        for: 30s
        labels:
          severity: warning
        annotations:
          summary: "Scrape duration too long"
          description: "Prometheus scrape duration exceeded 1s."

  - name: flask-app-metrics-alerts
    rules:

      - alert: HighRequestRate
        expr: rate(request_count_total[1m]) > 1
        for: 15s
        labels:
          severity: warning
        annotations:
          summary: "High request rate detected"
          description: "The Flask app is receiving more than 1 request/sec for the past minute."

      - alert: ZeroRequestRate
        expr: rate(request_count_total[1m]) == 0
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "No traffic to Flask App"
          description: "Flask app has received no requests for the past minute."

      - alert: HighRequestLatency
        expr: flask_http_request_duration_seconds_sum / flask_http_request_duration_seconds_count > 0.8
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "High request latency"
          description: "Flask app response time is averaging more than 0.8s over 30s."

      - alert: SpikeInLatency
        expr: increase(flask_http_request_duration_seconds_sum[1m]) > 5
        for: 15s
        labels:
          severity: warning
        annotations:
          summary: "Latency spike observed"
          description: "Total latency increased significantly in the last minute."

      - alert: ErrorStatusRate
        expr: rate(flask_http_request_errors_total[1m]) > 0.1
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "HTTP error rate is high"
          description: "More than 10% of requests are returning error responses."

  - name: loki-log-rules
    rules:
      - alert: HighRequestLatency
        expr: flask_request_latency_seconds_sum / flask_request_latency_seconds_count > 0.6
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High Request Latency"
