global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 1h
  receiver: 'gmail-notifications'
  routes:
    - match:
        severity: critical
      receiver: 'gmail-notifications'
    - match:
        severity: warning
      receiver: 'webhook-notifications'

receivers:
  - name: 'gmail-notifications'
    email_configs:
      - to: 'samuelsudeep9@gmail.com'
        from: 'ayyalasamuelsudeep@gmail.com'
        smarthost: 'smtp.gmail.com:587'
        auth_username: 'ayyalasamuelsudeep@gmail.com'
        auth_identity: 'ayyalasamuelsudeep@gmail.com'
        auth_password: 'chda nvfz esly srol'
        require_tls: true

  - name: 'webhook-notifications'
    webhook_configs:
      - url: 'http://webhook:9000/'
        send_resolved: true
