global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 1h
  receiver: 'gmail-notifications'
  routes:
    - match:
        severity: critical
      receiver: 'gmail-notifications' 

receivers:
  - name: 'gmail-notifications'
    email_configs:
      - to: ${EMAIL_RECEIVER}
        from: ${EMAIL_USERNAME}
        smarthost: 'smtp.gmail.com:587'
        auth_username: ${EMAIL_USERNAME}
        auth_identity: ${EMAIL_USERNAME}
        auth_password: ${EMAIL_PASSWORD}
        require_tls: true
