version: '3.8'

services:
  flask-app:
    build: ./python-flask-app
    container_name: flask-app
    ports:
      - "5000:5000"
    networks:
      - aiops-net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - aiops-net

networks:
  aiops-net:
