version: '3.8'

services:
  flask-app:
    build: ../Week1 - Monitoring Stack/python-flask-app
    container_name: flask-app
    ports:
      - "5000:5000"
    volumes:
      - logs:/var/log
    networks:
      - aiops-net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./rules/alert_rules.yml:/etc/prometheus/rules/alert_rules.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
    networks:
      - aiops-net

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    volumes:
      - ./alertmanager/config.yml:/etc/alertmanager/config.yml
    command:
      - '--config.file=/etc/alertmanager/config.yml'
    ports:
      - "9093:9093"
    networks:
      - aiops-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    networks:
      - aiops-net

volumes:
  logs:

networks:
  aiops-net:
    driver: bridge
