
version: '3.8'

services:
  flask-app:
    build: ../Week1 - Monitoring Stack/python-flask-app
    container_name: flask-app
    ports:
      - "5000:5000"
    volumes:
      - logs:/var/log
    networks:
      - aiops-net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./rules/alert_rules.yml:/etc/prometheus/rules/alert_rules.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
    networks:
      - aiops-net

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    volumes:
      - ./alertmanager/config.yml:/etc/alertmanager/config.yml
    command:
      - '--config.file=/etc/alertmanager/config.yml'
    ports:
      - "9093:9093"
    networks:
      - aiops-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
      - loki
    networks:
      - aiops-net

  webhook:
    build:
      context: ./webhook
    container_name: webhook
    ports:
      - "9000:9000"
    volumes:
      - ./webhook:/app
    working_dir: /app
    command: python webhook_receiver.py
    networks:
      - aiops-net

  loki:
    image: grafana/loki:2.8.2
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki-data:/loki
      - ../Week1 - Monitoring Stack/loki/loki-config.yml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - aiops-net

  promtail:
    image: grafana/promtail:2.8.2
    container_name: promtail
    volumes:
      - ../Week1 - Monitoring Stack/loki/promtail-config.yml:/etc/promtail/promtail-config.yml
      - logs:/var/log
    command: -config.file=/etc/promtail/promtail-config.yml
    depends_on:
      - loki
    networks:
      - aiops-net

volumes:
  logs:
  loki-wal:

networks:
  aiops-net:
    driver: bridge
