name: Validate Week 2 Stack

on:
    push:
      branches:
        - master
    workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Validate Python Syntax (Flask & Webhook)
        run: |
          python -m py_compile "Week2 - Alerting and Incident Detection"/**/*.py

      - name: Validate Docker Compose File
        run: |
          docker compose -f "Week2 - Alerting and Incident Detection/docker-compose.yml" config

      - name: YAML Linting
        run: |
          pip install yamllint
          yamllint -c .yamllint.yml "Week2 - Alerting and Incident Detection"

      - name: Download Prometheus (for promtool)
        run: |
          wget https://github.com/prometheus/prometheus/releases/download/v2.52.0/prometheus-2.52.0.linux-amd64.tar.gz
          tar xvf prometheus-2.52.0.linux-amd64.tar.gz
          sudo mv prometheus-2.52.0.linux-amd64/promtool /usr/local/bin/

      - name: Prepare Prometheus config structure
        run: |
          mkdir -p /etc/prometheus/rules
          cp "Week2 - Alerting and Incident Detection/rules/alert_rules.yml" /etc/prometheus/rules/alert_rules.yml
          cp "Week2 - Alerting and Incident Detection/prometheus/prometheus.yml" /etc/prometheus/prometheus.yml
          promtool --version

      - name: Prometheus Config Validation
        run: |
          promtool check config "Week2 - Alerting and Incident Detection/prometheus/prometheus.yml"

      - name: Alert Rules Validation
        run: |
          promtool check rules "Week2 - Alerting and Incident Detection/rules/alert_rules.yml"
